#https://hub.docker.com/_/alpine
FROM alpine:3.10.1

RUN apk --update --allow-untrusted --repository http://dl-4.alpinelinux.org/alpine/edge/community/ add \
      tor \
    && rm -rf /var/cache/apk/* /tmp/* /var/tmp/*

RUN mkdir /var/lib/tor/hidden_service/
RUN chmod 700 /var/lib/tor/hidden_service

RUN echo "SocksPort 0.0.0.0:9050" >> /etc/tor/torrc
RUN echo "HiddenServiceDir /var/lib/tor/hidden_service" >> /etc/tor/torrc
RUN echo "HiddenServicePort 80 nginx:80" >> /etc/tor/torrc

EXPOSE 9050

CMD ["tor", "-f", "/etc/tor/torrc"]
