FROM php:7.2.18-fpm-alpine

ENV MEMCACHED_DEPS zlib-dev libmemcached-dev cyrus-sasl-dev
RUN apk add --no-cache --update libmemcached-libs zlib
RUN set -xe \
    && apk add --no-cache --update --virtual .phpize-deps $PHPIZE_DEPS \
    && apk add --no-cache --update --virtual .memcached-deps $MEMCACHED_DEPS \
    && pecl install memcached \
    && echo "extension=memcached.so" > /usr/local/etc/php/conf.d/20_memcached.ini \
    && rm -rf /usr/share/php7 \
    && rm -rf /tmp/* \
    && apk del .memcached-deps .phpize-deps \ 
	&& apk add --no-cache libpng libpng-dev gettext-dev git \
	&& docker-php-ext-install gd pdo_mysql gettext \ 
	&& apk del libpng-dev

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer 

COPY cronjobs /var/spool/cron/crontabs/root
COPY gitclone.sh /tmp/gitclone.sh
RUN chmod +x /tmp/gitclone.sh

CMD /usr/sbin/crond -fS | "php-fpm"
